@startuml

title __CONTROLLER's Class Diagram__\n

  namespace com.fonzp.controller {
    class com.fonzp.controller.Index {
        - configFile : File
        + index()
    }
  }
  

  namespace com.fonzp.controller {
    class com.fonzp.controller.LoadDataset {
        - ds : DataSource
        - modelFile : File
        + loadDataset()
    }
  }
  

  namespace com.fonzp.controller {
    class com.fonzp.controller.LoadDataset.Response {
        # message : String
        # success : Boolean
        + Response()
        + equals()
        + getMessage()
        + getSuccess()
        + hashCode()
        + setMessage()
        + setSuccess()
        + toString()
    }
  }
  

  namespace com.fonzp.controller {
    class com.fonzp.controller.LogGetter {
        - ds : DataSource
        + getLogs()
    }
  }
  

  namespace com.fonzp.controller {
    class com.fonzp.controller.LogGetter.Response {
        # data : Object
        # message : String
        # success : Boolean
        + Response()
        + equals()
        + getData()
        + getMessage()
        + getSuccess()
        + hashCode()
        + setData()
        + setMessage()
        + setSuccess()
        + toString()
    }
  }
  

  namespace com.fonzp.controller {
    class com.fonzp.controller.ModelPrediction {
        - context : ApplicationContext
        + predictModel()
    }
  }
  

  namespace com.fonzp.controller {
    class com.fonzp.controller.ModelTrainer {
        - configFile : File
        - context : ApplicationContext
        + trainModel()
    }
  }
  

  namespace com.fonzp.controller {
    class com.fonzp.controller.VarsGetter {
        - ds : DataSource
        + getVars()
    }
  }
  

  namespace com.fonzp.controller {
    class com.fonzp.controller.VarsGetter.Response {
        # message : String
        # success : Boolean
        # variables : ArrayList<String>
        + Response()
        + equals()
        + getMessage()
        + getSuccess()
        + getVariables()
        + hashCode()
        + setMessage()
        + setSuccess()
        + setVariables()
        + toString()
    }
  }
  

  com.fonzp.controller.LoadDataset +-down- com.fonzp.controller.LoadDataset.Response
  com.fonzp.controller.LogGetter +-down- com.fonzp.controller.LogGetter.Response
  com.fonzp.controller.VarsGetter +-down- com.fonzp.controller.VarsGetter.Response


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
